// Fetches the last few years of S&P 500 (GSPC.INDX) monthly closes from
// EOD Historical Data (eodhd.com) and writes them to data/spx-monthly.json.
// The Roth deck's slide-16 chart reads that file at page-load time.
//
// Requires EODHD_API_KEY in the environment. In CI this comes from the
// GitHub Actions secret of the same name (set with `gh secret set
// EODHD_API_KEY`). Locally, export it before running:
//
//   EODHD_API_KEY=your_key node scripts/update-spx.mjs
//
// Window: every completed month from January of (currentYear - 2) through
// last month. The chart always covers two full prior years + current YTD.

import fs from 'node:fs/promises';
import path from 'node:path';

const EODHD_BASE = 'https://eodhd.com/api';
const TICKER = 'GSPC.INDX'; // S&P 500 index on EODHD
const OUT_PATH = path.join('data', 'spx-monthly.json');
const FULL_YEARS_KEPT = 2;
const MONTH_NAMES = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

function getApiKey() {
  const key = process.env.EODHD_API_KEY;
  if (!key) {
    throw new Error(
      'EODHD_API_KEY is not set. In CI it should come from a GitHub Actions ' +
      'secret of the same name. Locally, export it before running:\n' +
      '  EODHD_API_KEY=your_key node scripts/update-spx.mjs'
    );
  }
  return key;
}

async function fetchEodhd() {
  const apiKey = getApiKey();
  // Pull from start of (currentYear - 5) to keep a small buffer beyond what
  // the deck actually displays. Filtering happens after we have the rows.
  const fromYear = new Date().getUTCFullYear() - 5;
  const url = `${EODHD_BASE}/eod/${TICKER}?api_token=${apiKey}&fmt=json&period=m&from=${fromYear}-01-01`;
  // Logged URL has the API key stripped — important for CI logs.
  console.log(`Fetching ${EODHD_BASE}/eod/${TICKER}?fmt=json&period=m&from=${fromYear}-01-01`);
  const res = await fetch(url, {
    headers: { 'User-Agent': 'roth-deck-spx-updater/1.0 (+https://github.com/ynsbiz3502/yields4u-static-decks)' },
  });
  if (!res.ok) throw new Error(`EODHD HTTP ${res.status}`);
  const arr = await res.json();
  if (!Array.isArray(arr) || arr.length === 0) {
    throw new Error('EODHD returned a non-array or empty response');
  }
  const rows = [];
  for (const o of arr) {
    if (!o || typeof o.date !== 'string') continue;
    const close = (typeof o.adjusted_close === 'number' && Number.isFinite(o.adjusted_close))
      ? o.adjusted_close
      : (typeof o.close === 'number' && Number.isFinite(o.close) ? o.close : null);
    if (close == null) continue;
    const [yStr, moStr] = o.date.split('-');
    const y = parseInt(yStr, 10);
    const mo = parseInt(moStr, 10);
    if (!Number.isFinite(y) || !Number.isFinite(mo) || mo < 1 || mo > 12) continue;
    rows.push({ y, mo, close, date: o.date });
  }
  // Defensive sort by date ascending (EODHD typically returns ascending already).
  rows.sort((a, b) => a.date.localeCompare(b.date));
  return rows;
}

async function main() {
  const rows = await fetchEodhd();
  if (rows.length === 0) throw new Error('No usable rows after parse');

  // We INCLUDE the in-progress current month — EODHD's monthly endpoint
  // returns the running close (the last completed trading day's close)
  // for that month. Using stale data ending at the prior month would
  // understate YTD; this way slide 16 reflects where the market actually
  // sits right now. The monthly bar for the in-progress month will tick
  // each time the script runs.
  const now = new Date();
  const currentYear = now.getUTCFullYear();

  // Window: Jan(currentYear - FULL_YEARS_KEPT) through whatever the latest
  // EODHD row is (including the in-progress current month).
  const startYear = currentYear - FULL_YEARS_KEPT;
  const windowed = rows.filter(r => r.y >= startYear);
  const trimmed = windowed.map(r => ({
    m: `${MONTH_NAMES[r.mo - 1]} ${String(r.y).slice(-2)}`,
    v: Math.round(r.close * 100) / 100,
  }));

  const out = {
    updated_at: new Date().toISOString(),
    source: `https://eodhd.com/api/eod/${TICKER}?period=m`,
    note: 'Auto-generated by scripts/update-spx.mjs from EOD Historical Data monthly closes for GSPC.INDX. Hand-editing is OK; the scheduled workflow will overwrite on its next run.',
    months: trimmed.length,
    series: trimmed,
  };

  await fs.mkdir(path.dirname(OUT_PATH), { recursive: true });
  await fs.writeFile(OUT_PATH, JSON.stringify(out, null, 2) + '\n');
  console.log(`Wrote ${trimmed.length} months to ${OUT_PATH}`);
  if (trimmed.length > 0) {
    console.log(`  first: ${trimmed[0].m} @ ${trimmed[0].v}`);
    console.log(`  last:  ${trimmed[trimmed.length - 1].m} @ ${trimmed[trimmed.length - 1].v}`);
  }
}

main().catch(err => {
  console.error('update-spx failed:', err);
  process.exit(1);
});
