// Fetches the last few years of S&P 500 (^GSPC) monthly closes from Yahoo
// Finance (no API key needed) and writes them to data/spx-monthly.json. The
// Roth deck's slide-16 chart reads that file at page-load time.
//
// Run locally:
//   node scripts/update-spx.mjs
//
// Designed for the monthly GitHub Action in .github/workflows/update-spx.yml.
//
// Notes:
//   - Yahoo's monthly bar for the in-progress month includes a partial close
//     that updates intraday. We drop it; the deck shouldn't show a close that
//     could change tomorrow.
//   - Window: every completed month from January of (currentYear - 2) through
//     last month. So the chart always covers two full prior years + YTD.

import fs from 'node:fs/promises';
import path from 'node:path';

const YAHOO_URL = 'https://query1.finance.yahoo.com/v8/finance/chart/%5EGSPC?interval=1mo&range=5y';
const OUT_PATH = path.join('data', 'spx-monthly.json');
const FULL_YEARS_KEPT = 2;
const MONTH_NAMES = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

async function fetchYahoo() {
  const res = await fetch(YAHOO_URL, {
    headers: {
      // Yahoo serves 401 to bare/curl-like UAs; mimic a generic browser.
      'User-Agent': 'Mozilla/5.0 (compatible; roth-deck-spx-updater/1.0; +https://github.com/ynsbiz3502/yields4u-static-decks)',
      'Accept': 'application/json',
    },
  });
  if (!res.ok) throw new Error(`Yahoo HTTP ${res.status}`);
  const json = await res.json();
  const result = json && json.chart && json.chart.result && json.chart.result[0];
  if (!result) throw new Error('Yahoo response missing chart.result[0]');
  const timestamps = result.timestamp || [];
  const closes = (result.indicators && result.indicators.quote && result.indicators.quote[0]
    && result.indicators.quote[0].close) || [];
  if (timestamps.length === 0 || closes.length === 0) {
    throw new Error('Yahoo response had no timestamps/closes');
  }
  if (timestamps.length !== closes.length) {
    throw new Error(`Yahoo timestamp/close length mismatch (${timestamps.length} vs ${closes.length})`);
  }
  const rows = [];
  for (let i = 0; i < timestamps.length; i++) {
    const close = closes[i];
    if (close == null || !Number.isFinite(close)) continue;
    const d = new Date(timestamps[i] * 1000);
    rows.push({ y: d.getUTCFullYear(), mo: d.getUTCMonth() + 1, close, date: d.toISOString().slice(0, 10) });
  }
  return rows;
}

async function main() {
  console.log(`Fetching ${YAHOO_URL}`);
  const rows = await fetchYahoo();
  if (rows.length === 0) throw new Error('No usable rows after parse');

  const now = new Date();
  const currentYear = now.getUTCFullYear();
  const currentMonth = now.getUTCMonth() + 1;
  // Drop the in-progress current month — its close is still moving.
  const completed = rows.filter(r => (r.y < currentYear) || (r.y === currentYear && r.mo < currentMonth));
  if (completed.length === 0) throw new Error('No completed months after current-month filter');

  // Window: Jan(currentYear - FULL_YEARS_KEPT) through last completed month.
  const startYear = currentYear - FULL_YEARS_KEPT;
  const windowed = completed.filter(r => r.y >= startYear);
  const trimmed = windowed.map(r => ({
    m: `${MONTH_NAMES[r.mo - 1]} ${String(r.y).slice(-2)}`,
    v: Math.round(r.close * 100) / 100,
  }));

  const out = {
    updated_at: new Date().toISOString(),
    source: YAHOO_URL,
    note: 'Auto-generated by scripts/update-spx.mjs from Yahoo Finance monthly closes for ^GSPC. Hand-editing is OK; the scheduled workflow will overwrite on its next run.',
    months: trimmed.length,
    series: trimmed,
  };

  await fs.mkdir(path.dirname(OUT_PATH), { recursive: true });
  await fs.writeFile(OUT_PATH, JSON.stringify(out, null, 2) + '\n');
  console.log(`Wrote ${trimmed.length} months to ${OUT_PATH}`);
  if (trimmed.length > 0) {
    console.log(`  first: ${trimmed[0].m} @ ${trimmed[0].v}`);
    console.log(`  last:  ${trimmed[trimmed.length - 1].m} @ ${trimmed[trimmed.length - 1].v}`);
  }
}

main().catch(err => {
  console.error('update-spx failed:', err);
  process.exit(1);
});
